/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseUtils;

import com.nct.framework.common.LogUtil;
import com.nct.framework.dbconn.ClientManager;
import com.nct.framework.dbconn.ManagerIF;
import entities.DB.CineChannelEnt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;

/**
 *
 * @author MrFlex
 */
public class CineServiceUtils {
    private static final Logger logger = LogUtil.getLogger(DatabaseServiceUtils.class);
    
    public static long CreateCineChanel(CineChannelEnt channelEnt) {
        long idReturn = 0L;
        ManagerIF cm = ClientManager.getInstance("hdbox_server_db");
        Connection cnn = cm.borrowClient();
        try {
            String query = "INSERT INTO `Cine_Channel` (`Name`, `Image`, `Cover`, `Categories`, `Description`, `Country`, `Time`, `Tags`, `ArtistIds`, `Status`)"
                    + " VALUE (?,?,?,?,?,?,?,?,?,?);";
            
            PreparedStatement stmt = cnn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            stmt.setString(1, channelEnt.Name);
            stmt.setString(2, channelEnt.Thumb);
            stmt.setString(3, channelEnt.Cover);
            stmt.setString(4, StringUtils.join(channelEnt.Categories, ","));
            stmt.setString(5, channelEnt.Description);
            stmt.setString(6, channelEnt.Country);
            stmt.setString(7, channelEnt.Time);
            stmt.setString(8, StringUtils.join(channelEnt.Tags, ","));
            stmt.setString(9, StringUtils.join(channelEnt.ArtistIds, ","));
            stmt.setInt(10, channelEnt.Status);
            
            int result = stmt.executeUpdate();
            if(result>0){
                ResultSet tableKeys = stmt.getGeneratedKeys();
                if(tableKeys.next()){
                    long autoGeneratedID = tableKeys.getLong(1);
                    idReturn = (autoGeneratedID>0) ? autoGeneratedID : 0;
                }
            }
        } catch (SQLException ex){
            logger.error(LogUtil.stackTrace(ex));
        } finally {
            cm.returnClient(cnn);
        }
        
        return idReturn;
    }
}
